runtime: java
env: flex
service: default
runtime_config:
  jdk: openjdk8
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5
env_variables:
  SPRING_PROFILES_ACTIVE: "mysql"
handlers:
  - url: /.*
    script: this field is required, but ignored
# [END gae_flex_quickstart_yaml]
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
